version: 2
updates:
  - package-ecosystem: "python"
    directory: "/" # Update this if your requirements files are in a subdirectory
    schedule:
      interval: "daily" # You can set this to "weekly" or "monthly" if preferred
    ignore:
      - dependency-name: "some-package-to-ignore" # List any packages you want to ignore updates for
        versions: ["<2.0.0"] # Specify version constraints for ignoring updates
  - package-ecosystem: "pip"
    directory: "/" # Adjust if needed
    schedule:
      interval: "daily" # Set to "weekly" or "monthly" if needed
    ignore:
      - dependency-name: "another-package-to-ignore"
        versions: ["<3.0.0"]
